# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from portal_api import portal_api_pb2 as portal__api_dot_portal__api__pb2


class PlayStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EnrolPlayer = channel.unary_unary(
        '/Play/EnrolPlayer',
        request_serializer=portal__api_dot_portal__api__pb2.Player.SerializeToString,
        response_deserializer=portal__api_dot_portal__api__pb2.Status.FromString,
        )


class PlayServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def EnrolPlayer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EnrolPlayer': grpc.unary_unary_rpc_method_handler(
          servicer.EnrolPlayer,
          request_deserializer=portal__api_dot_portal__api__pb2.Player.FromString,
          response_serializer=portal__api_dot_portal__api__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Play', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
